image: php:8.0.2
pipelines:
  branches:
    master:
      - step:
          name: Deploy to development
          deployment: Production
          script:
            - pipe: atlassian/ssh-run:0.2.2
              variables:
                SSH_USER: "craftcms"
                SERVER: "178.128.206.62"
                COMMAND: "./deploy.sh"