field: 48b393c6-8937-4f82-9402-a1d6bd982171 # Page Content
fieldLayouts:
  50b20caa-ba68-4242-8186-7c3b2fb040d2:
    tabs:
      -
        elements:
          -
            fieldUid: 11dfb393-6b7d-48eb-99f1-0be61d09d736 # Custom Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 26442f4f-35dc-488d-80da-e443cfc19968 # Hide Title?
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 84433a26-be49-4cba-b6e9-45a66eda95d3 # Module ID
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  11dfb393-6b7d-48eb-99f1-0be61d09d736: # Custom Title
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: customTitle
    instructions: "Custom title for driftsmeldinger data.\r\nData will be automatically shown from Globals - Driftsmeldinger Data"
    name: 'Custom Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  26442f4f-35dc-488d-80da-e443cfc19968: # Hide Title?
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: hideTitle
    instructions: 'If you wish to hide title (global or this one), select this.'
    name: 'Hide Title?'
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  84433a26-be49-4cba-b6e9-45a66eda95d3: # Module ID
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: moduleId
    instructions: ''
    name: 'Module ID'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: driftsmeldingerData
name: 'Driftsmeldinger Data'
sortOrder: 9
