fieldLayouts:
  1dad11b1-9f1a-48b6-8376-2689a02fc9ff:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: a856f8a8-6e0b-4f19-9da9-ee9ae49387dd # Article Excerpt
            instructions: 'Short customer description that will be shown on customer cards.'
            label: 'Customer Excerpt'
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            type: craft\fieldlayoutelements\HorizontalRule
          -
            fieldUid: dab2ed87-f018-40d2-b65d-dc2233d0a211 # Article Image
            instructions: ''
            label: 'Featured Image'
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            type: craft\fieldlayoutelements\HorizontalRule
          -
            fieldUid: b09757a1-537c-4ffb-9251-c9ae32e5e67b # Related Services
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Kunder Data'
        sortOrder: 1
      -
        elements:
          -
            fieldUid: b428c6c7-61b0-430f-aaaf-76e0c36a018b # Page Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Kunder Content'
        sortOrder: 2
      -
        elements:
          -
            fieldUid: 70b04be1-ca61-4f64-8983-47f37be11675 # Page Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 30d7b80d-5ede-47a8-8b53-9a193547c750 # Page Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7cec95cc-1712-4f28-b46f-812763ed6230 # Page URL
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b395b4bc-4cdd-4edf-a06c-5c3ed9e758cb # Page Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ba9a3316-329c-4df5-8ddd-9abc7ac9f7d7 # Page Image Alt
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: SEO
        sortOrder: 3
handle: default
hasTitleField: true
name: Default
section: f3c3c199-9112-4d05-8909-14670dd11c5f # Dira Customers
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
