columnSuffix: vjjpxfyg
contentColumnType: string
fieldGroup: a67608a9-f9c9-4b46-8b52-1d1b08ddf5c8 # Globals - Site Contact Data
handle: contactEmail
instructions: ''
name: 'Contact Email'
searchable: false
settings:
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Email
