columnSuffix: lyowrfbz
contentColumnType: text
fieldGroup: a67608a9-f9c9-4b46-8b52-1d1b08ddf5c8 # Globals - Site Contact Data
handle: contactPhone
instructions: ''
name: 'Contact Phone'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
