columnSuffix: hbbaanmd
contentColumnType: text
fieldGroup: 668d7ba4-39e2-4a10-80a8-51637517741b # Globals - Driftsmeldinger Data
handle: gddTitle
instructions: 'Add title for driftsmeldinger boxes.'
name: 'Driftsmeldinger Data Title'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
