columnSuffix: vcozdhsp
contentColumnType: text
fieldGroup: b0fd6549-02a5-4fcf-b6e5-cee1a7578a6e # Single - Customers
handle: heroMessage
instructions: 'Add message that will be shown after 2 customers in listing.'
name: 'Hero Message'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '2'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
