columnSuffix: yakjeask
contentColumnType: text
fieldGroup: fd739832-07b5-48f8-b324-f892f7474a3d # Header - Home
handle: hhHelpBoxTitle
instructions: ''
name: 'Header Help Box Title'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
