fieldLayouts:
  4274f91f-a6bc-485e-8677-d2303dcb2629:
    tabs:
      -
        elements:
          -
            fieldUid: 14299cac-2465-48a7-b136-f88a9b1af2cc # Show Driftsmeldinger Status Bar?
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            type: craft\fieldlayoutelements\HorizontalRule
          -
            fieldUid: b40adbd6-8340-4629-92c9-0a0ca1645886 # Driftsmeldinger Data Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 8c996efa-4ce4-4718-8b87-2cc4d9651b05 # Driftsmeldinger List Boxes
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Driftsmeldinger Data'
        sortOrder: 1
handle: driftsmeldingerData
name: 'Driftsmeldinger Data'
sortOrder: 5
