fieldLayouts:
  b29c3cc5-3aaa-476a-ae3b-8263705767e2:
    tabs:
      -
        elements:
          -
            fieldUid: 7ed929cb-4184-4ca2-b087-3526c87aa38c # Contact Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 3ffdb739-a429-4df1-be16-07f6252ad2e4 # Contact Phone
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: bdb763f6-73d0-4fe7-a326-df63c11f407a # Contact Email
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
        name: 'Contact Data'
        sortOrder: 1
handle: siteContactData
name: 'Site Contact Data'
sortOrder: 4
