fieldLayouts:
  7f8b6747-c92c-49f6-9491-03503e85dea7:
    tabs:
      -
        elements:
          -
            fieldUid: 79deb152-a2fa-41a3-8fa2-e08ac08c357e # Site Logo
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            type: craft\fieldlayoutelements\HorizontalRule
          -
            fieldUid: 45eafd59-0c55-4b2e-9a35-b00733a1d9a6 # Left Link URL
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 75f75307-13f3-4be8-9ea5-a4f0618befbe # Left Link Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            type: craft\fieldlayoutelements\HorizontalRule
          -
            fieldUid: 3426bbd8-ae24-4099-88d4-f6fe3f6b1e18 # Use Custom Navigation?
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 2202461d-285c-4b02-9aa1-66fea5228786 # Site Custom Navigation
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Site Navigation'
        sortOrder: 1
handle: siteNav
name: 'Site Navigation'
sortOrder: 2
