defaultPlacement: end
enableVersioning: true
handle: customers
name: 'Dira Customers'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  27aff492-2400-42d9-878a-bd134e93ebd6: # $DEFAULT_SITE_NAME
    enabledByDefault: true
    hasUrls: true
    template: page/customers/single
    uriFormat: 'vår-kunde/{slug}'
structure:
  maxLevels: 1
  uid: 058b43b5-01eb-48c8-a576-f57400d89ed8
type: structure
