defaultPlacement: end
enableVersioning: true
handle: services
name: 'Dira Services'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  27aff492-2400-42d9-878a-bd134e93ebd6: # $DEFAULT_SITE_NAME
    enabledByDefault: true
    hasUrls: true
    template: page/services/single
    uriFormat: 'vår-tjenest/{slug}'
structure:
  maxLevels: 1
  uid: f339b57b-d10d-4454-b2ca-d7ca2cb0d951
type: structure
