name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy app
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          password: ${{secrets.SSH_PASSWORD}} # Private or public key of the server
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into
     
          script: |
            cd /var/www/html/dira.no
            git pull
            composer install --no-interaction
            php craft up
            php craft clear-caches/all
            cd css-js
            yarn install
            yarn run prod
            sudo chmod -R 755 /var/www/html/
