name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy app
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          password: ${{secrets.SSH_PASSWORD}} # Private or public key of the server
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into
     
          script: |
            cd /var/www/html/dira.no
            sudo -u www-data bash -c 'git pull'
            sudo -u www-data bash -c 'composer install --no-interaction'
            sudo -u www-data bash -c 'php craft up'
            sudo -u www-data bash -c 'php craft clear-caches/all'
            cd css-js
            sudo -u www-data bash -c 'yarn install'
            sudo -u www-data bash -c 'yarn run prod'
